name: Update Manga Deals (daily)

on:
  schedule:
    - cron: "0 0 * * *"   # 毎日9時（日本時間）に実行
  workflow_dispatch:       # 手動でも実行できるようにする

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: npm run update:manga

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update deals_manga.json (daily)"
          file_pattern: deals_manga.json
